
# main.py
# Generated by the Assistant for an AI-Powered Pretyping Evaluation Experiment

from flask import Flask, render_template, redirect, request
from typing_test import measure_typing

app = Flask(__name__)

@app.route('/')
def index():
    """
    Main landing page for participants to access.
    """
    return render_template('index.html')

@app.route('/typing_test')
def typing_test():
    """
    Page where participants take the typing test.
    """
    return render_template('typing_test.html')

@app.route('/results')
def results():
    """
    Page that displays the results of the typing test.
    """
    name = request.args.get('name')
    age = request.args.get('age')
    typing_skill = request.args.get('typing_skill')
    before_wpm, before_acc = measure_typing(request.args.get('before_text'))
    after_wpm, after_acc = measure_typing(request.args.get('after_text'))
    return render_template('results.html', name=name, age=age, typing_skill=typing_skill, before_wpm=before_wpm, before_acc=before_acc, after_wpm=after_wpm, after_acc=after_acc)

@app.route('/pretyping_app')
def pretyping_app():
    """
    Handles the logic associated with the pretyping application.
    """
    return render_template('pretyping_app.html')

@app.route('/pretyping_app/results')
def pretyping_app_results():
    """
    Routes participants to the typing test again after they have completed the pretyping application.
    """
    return redirect('/typing_test')

if __name__ == '__main__':
    app.run(debug=True)
